### ISSUE TITLE
Question about SampleDialogPresenter.cs

### ISSUE THREAD

**Issue by vector-man** [derfsplat/MiniMVP#2]
In SampleDialogPresenter.cs, you have the following comment: "//todo: have mainform implement IHostWinForms iface so we can get owner via IHOstWinForms dep passed to ctor"

Do you have any information on how this would be done? Thanks!

**Comment by derfsplat** [comment]
If I recall correctly (from 3+ years ago :) ) this interface i referenced was in another project that's not in GH.  Let me check tonight and see if I can dig it up and give you something a little more useful!

**Comment by derfsplat** [comment]
This is what I meant: https://github.com/derfsplat/MiniMVP/commit/79e857f86824db910578224f3765be0e8f18c9ed

[The TODO](https://github.com/derfsplat/MiniMVP/commit/79e857f86824db910578224f3765be0e8f18c9ed#diff-b4b769f6ba30bc8872b0624baef9736cL22) was in reference to removing the method dependency on `IWin32Window` - it gets old carting that around to every method that has to deal with UI and wants to properly "own" dialogs.  I prefer passing that once in the constructor of a presenter and calling it a day.
